### ISSUE TITLE
PhpStorm gets opened twice

### ISSUE THREAD

**Issue by ricardgf** [hansdubois/aflfred-phpstorm-opener#2]
If phpStorm it's not opened it gets opened twice with the same project.
If I run the command manually "open -a /Applications/PhpStorm.app {project dir}" it also happens.

I've also tried to solve it by using the "Create command line launcher..." in PhpStorm Tools and replacing the "open -a /Applications/PhpStorm.app" with "pstorm", but then it's not opening at all.

Any idea on how to solve it?

PD: Maybe it's not the right place to post, but since i haven't found any forum post here it goes. Thank you

**Comment by hansdubois** [comment]
That's wierd, PHPStorm should not open it self twice. What version are you using?

**Comment by ricardgf** [comment]
9.0.2,  The latest one.
I've checked with another collegue at work and it's the same behaviour as mine, it gets opened twice.
It's weird !

Thank You!

**Comment by ricardgf** [comment]
Ok, 
I finally managed to solve it by disabling "reopen last project on startup".
With this option enabled and even if you have closed Phpstorm without any project opened, if you open phpstorm with "open -a ..." somehow the project specified in the command line gets opened twice.

It seems a Phpstorm bug, because if I open it manually it does not open any project with the option enabled.

Thank you for your help.

**Comment by hansdubois** [comment]
Cool! Thanks for figuring out! Was not able to figure it out with a colleague of mine.

Added it as a note to the Readme. 

Thanks for reporting!
